---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deployment-sshfs
spec:
  accessModes:
    - ReadWriteMany  # In this example, multiple Pods consume the same PVC.
  resources:
    requests:
      storage: 10Gi
  storageClassName: sshfs-csi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-sshfs
spec:
  replicas: 1
  selector:
    matchLabels:
      name: deployment-sshfs
  template:
    metadata:
      name: deployment-sshfs
      labels:
        name: deployment-sshfs
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: deployment-sshfs
          image: mcr.microsoft.com/oss/nginx/nginx:1.19.5
          command:
            - "/bin/bash"
            - "-c"
            - set -euo pipefail; while true; do echo $(hostname) $(date) >> /mnt/sshfs/outfile; sleep 1; done
          volumeMounts:
            - name: sshfs
              mountPath: "/mnt/sshfs"
      volumes:
        - name: sshfs
          persistentVolumeClaim:
            claimName: pvc-deployment-sshfs
