---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sshfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sshfs-csi
  mountOptions:
    - sshfsvers=3.7.3
  csi:
    driver: sshfs.csi.k8s.io
    readOnly: false
    volumeHandle: unique-volumeid  # make sure it's a unique id in the cluster
    volumeAttributes:
      server: sshfs-server.default.svc.cluster.local
      share: /
      port: "2222"
      private-key-name: "nginx-pod-rsa-key"  # make sure it's a private key secret
      private-key-namespace: "default"
      user: "linuxserver.io"
