---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sshfs-dynamic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: sshfs-csi
