---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-sshfs-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-sshfs
  storageClassName: sshfs-csi
