---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sshfs-csi
provisioner: sshfs.csi.k8s.io
parameters:
  server: sshfs-server.default.svc.cluster.local
  share: /
  port: "2222"
  private-key-name: "nginx-pod-rsa-key"  # make sure it's a private key secret
  private-key-namespace: "default"
  user: "linuxserver.io"
  # csi.storage.k8s.io/provisioner-secret is only needed for providing mountOptions in DeleteVolume
  # csi.storage.k8s.io/provisioner-secret-name: "mount-options"
  # csi.storage.k8s.io/provisioner-secret-namespace: "default"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - sshfsvers=3.7.3
